name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  PROJECT: "morpheus"
  SERVICE: "stats-backend"
  RESOURCE_GROUP: mor-metrics_group
  ACR_REGISTRY_NAME: morpheusai

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.ACR_REGISTRY_NAME }}
    
    - name: Build and push container image
      run: |
        docker build . -t ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT }}-${{ env.SERVICE }}:${{ github.sha }}
        docker push ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT }}-${{ env.SERVICE }}:${{ github.sha }}

  staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
    env:
      ENVIRONMENT: "staging"
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.PROJECT }}-${{ env.SERVICE }}-${{ env.ENVIRONMENT }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT }}-${{ env.SERVICE }}:${{ github.sha }}

  prod:
    needs: [build, staging]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: 'Prod'
    env:
      ENVIRONMENT: "prod"
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.PROJECT }}-${{ env.SERVICE }}-${{ env.ENVIRONMENT }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT }}-${{ env.SERVICE }}:${{ github.sha }}