name: Deploy to Azure Web App

on:
  push:
    branches: [ main, croc/ci-cd-updates]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  PROJECT: "morpheus"
  SERVICE: "stats-backend"
  RESOURCE_GROUP: mor-metrics_group
  ACR_REGISTRY_NAME: morpheusai
  CONTAINER_IMAGE_NAME: $PROJECT-$SERVICE

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.ACR_REGISTRY_NAME }}
    
    - name: Build and push container image
      run: |
        docker build . -t ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:latest
        docker push ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }} --all-tags

  staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
    env:
      ENV: "staging"
      FULL_SERVICE_NAME: $CONTAINER_IMAGE_NAME-$ENV
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.FULL_SERVICE_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}

  prod:
    needs: [build, staging]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: 'Prod'
    env:
      ENV: "prod"
      FULL_SERVICE_NAME: $CONTAINER_IMAGE_NAME-$ENV
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.FULL_SERVICE_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}