# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - mor-stats-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt -v --use-feature=fast-deps
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Create Google Sheets credentials
        run: |
          mkdir -p sheets_config
          echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" > sheets_config/credentials.json
          chmod 644 sheets_config/credentials.json

      - name: Make startup script executable
        run: |
          chmod +x startup.sh

      - name: Zip artifact for deployment
        run: |
          find . -type f -not -path '*/\.*' -not -path '*/venv/*' -not -path '*/__pycache__/*' -not -name '*.pyc' | zip release.zip -@

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mor-stats-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_4b191a571e8a4b249fd018b98313c59d }}